### ISSUE TITLE
BNode' object has no attribute 'get_all'

### ISSUE THREAD

**Issue by PonteIneptique** [Capitains/MyCapytain#114]
```
AssertionError: invalid Element proxy at 139653626993608
[2017-02-22 11:02:34 +0000] [3393] [ERROR] Error handling request /text/urn:cts:latinLit:phi1294.phi002.perseus-lat2/passage/1.pr.1-1.pr.20/latin-classique-martial-epigrammata-epigrammata
Traceback (most recent call last):
  File "/local/www-data/capitains-app/venvs/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 130, in handle
    self.handle_request(listener, req, client, addr)
  File "/local/www-data/capitains-app/venvs/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 171, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/local/www-data/capitains-app/venvs/lib/python3.5/site-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/local/www-data/capitains-app/venvs/lib/python3.5/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/local/www-data/capitains-app/venvs/lib/python3.5/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/local/www-data/capitains-app/venvs/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/local/www-data/capitains-app/venvs/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/local/www-data/capitains-app/venvs/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/local/www-data/capitains-app/venvs/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/local/www-data/capitains-app/venvs/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/local/www-data/capitains-app/venvs/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/local/www-data/capitains-app/venvs/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/local/www-data/capitains-app/venvs/lib/python3.5/site-packages/flask_nemo/__init__.py", line 762, in route
    return self.route(getattr(instance, name), **kwargs)
  File "/local/www-data/capitains-app/venvs/lib/python3.5/site-packages/flask_nemo/__init__.py", line 833, in route
    new_kwargs = fn(**kwargs)
  File "/local/www-data/capitains-app/venvs/lib/python3.5/site-packages/flask_caching/__init__.py", line 646, in decorated_function
    rv = f(*args, **kwargs)
  File "/local/www-data/capitains-app/venvs/lib/python3.5/site-packages/flask_nemo/__init__.py", line 632, in r_passage
    text = self.get_passage(objectId=objectId, subreference=subreference)
  File "/local/www-data/capitains-app/venvs/lib/python3.5/site-packages/flask_caching/__init__.py", line 646, in decorated_function
    rv = f(*args, **kwargs)
  File "/local/www-data/capitains-app/venvs/lib/python3.5/site-packages/flask_nemo/__init__.py", line 405, in get_passage
    metadata=True
  File "/local/www-data/capitains-app/venvs/lib/python3.5/site-packages/capitains_nautilus/cts/resolver.py", line 339, in getTextualNode
    passage.set_metadata_from_collection(text_metadata)
  File "/local/www-data/capitains-app/venvs/lib/python3.5/site-packages/MyCapytain/resources/prototypes/text.py", line 452, in set_metadata_from_collection
    for node in textgroup.metadata.get_all(NAMESPACES.CTS.groupname):
AttributeError: 'BNode' object has no attribute 'get_all'
```

**Comment by PonteIneptique** [comment]
The issue seems to come from pickling resource and sharing information across them, more specifically Metadata.getOr failing to build a new metadata object but rather coming up with a BNode

**Comment by PonteIneptique** [comment]
Fixed by moving away Metadata from BNode inheritance
