### ISSUE TITLE
XPath with double "//" fail to retrieve passages when they succeed in finding texts references

### ISSUE THREAD

**Issue by PonteIneptique** [Capitains/MyCapytain#137]
Source : https://github.com/PerseusDL/canonical-latinLit/issues/226

# Context
After trying to find all texts, we get for each texts the list of references it has. For [one text](https://github.com/PerseusDL/canonical-latinLit/blob/2dd926de291d002f35d2b3e255a3b97634084554/.travis.yml) with XPath : 

```xml
         <refsDecl n="CTS">
            <cRefPattern n="line" matchPattern="(\w+).(\w+)"
              replacementPattern="#xpath(/tei:TEI/tei:text/tei:body/tei:div//tei:div[@subtype='poem' and @n='$1']//tei:l[@n='$2'])">
               <p>This pointer pattern extracts poem and line</p>
            </cRefPattern>
           <cRefPattern n="poem" matchPattern="(\w+)"
              replacementPattern="#xpath(/tei:TEI/tei:text/tei:body/tei:div//tei:div[@subtype='poem' and @n='$1'])">
             <p>This pointer pattern extracts poem</p>
           </cRefPattern>
         </refsDecl>
```

we fail to retrieve one passage, namely 5.1. It happens to be the first XML element that has both a l[n=1] and a div[n=1].

# Expected output
We should retrieve the content 
```xml
           <div type="textpart" n="5" subtype="poem">
               <head>Tetrasticha</head>
                <div type="textpart" n="praef" subtype="section">
                  <!-- Here --><l n="1">NUNC et praedictos et regni sorte sequentes</l>
```

# Actual output
```shell
Traceback (most recent call last):
  File "/MyCapytain/tests/test_ad_hoc.py", line 20, in test_passage_extraction_fail_when_reffs_are_found
    passages.append(interactive_text.getTextualNode(reff))
  File "/MyCapytain/MyCapytain/resources/texts/local/capitains/cts.py", line 88, in getTextualNode
    root = passageLoop(xml, root, start, end)
  File "/MyCapytain/MyCapytain/common/utils.py", line 375, in passageLoop
    queue_2
  File "/MyCapytain/MyCapytain/common/utils.py", line 375, in passageLoop
    queue_2
  File "/MyCapytain/MyCapytain/common/utils.py", line 375, in passageLoop
    queue_2
  File "/MyCapytain/MyCapytain/common/utils.py", line 350, in passageLoop
    result_1, loop = performXpath(parent, current_1)
  File "/MyCapytain/MyCapytain/common/utils.py", line 253, in performXpath
    return result[0], loop
IndexError: list index out of range
```

**Comment by PonteIneptique** [comment]
Fixed by @1ce2276
